title: Infotehnoloogia ettevõtjale
baseurl: "https://agiil.github.io/IT"

defaults:
  -
    scope:
      path: "" # Kõik failid
    values:
      layout: "IT"
      draft: "false"
      sidebar: "false"
